title: Samudra Herath # your name (or website title) here
logo: "/images/Samudra2_.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks), Following data-driven dreams that transform real-world challenges to create a better tomorrow.
  Data Scientist | Machine Learning Scientist | PhD  
  <br><br>
  <i>"I see the beauty now of statistics and machine learning and the stories that a great deal of data can tell us."
  <br><br>
  <a href="https://www.linkedin.com/in/sdherath/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
