title: Samudra Herath # your name (or website title) here
logo: "/images/Samudra2_.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate Machine Learning/Data Scientist dedicated to utilising data science, machine learning (ML), and statistics to address real-world challenges. 
  With a continuous learning mindset and strong research orientation, I strive to make meaningful contributions through innovative problem-solving to create a better society. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sdherath/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
